name: workflow with multiple stages

on: 
  push:

jobs:
  job-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
      - run: pwd

  job-on-windows:
    name: a job running on windows
    runs-on: windows-latest
    steps:
      - name: first step in windows job
        run
